### PR TITLE
Responsiveness

### PR DESCRIPTION
**Pull request by sanathkumar26700**
Made moview E-com store responsive to mobile view (under 400px), used media queries to make few major changes in navbar, product-list page and landing page.

Also added footer to wish-list page, cart page.

### CODE REVIEW

**Review by Amandeep-sinha — APPROVED** [review]
looks good to merge

**Review by someshtiwarii — APPROVED** [review]
looks good to merge!

**Review by MarkVed17 — APPROVED** [review]
image

Doesn't the 👀 emoji look out of place in mobile view? Also, you may move the filters to a sidebar menu later. This will create some more space for the product cards. Rest everything is responsive.

**Comment by sanathkumar26700** [comment]
> image
> 
> Doesn't the 👀 emoji look out of place in mobile view? Also, you may move the filters to a sidebar menu later. This will create some more space for the product cards. Rest everything is responsive.



This is the layout in my mobile,
I have set media query for mobile view under 400px.
I think your device is wider😅

**Pull request merged**
